services:
  congratulations_nginx:
    ports:
      - 80:80
    image: nginx:alpine
    restart: unless-stopped
    container_name: congratulations_nginx_container
    volumes:
      - ./nginx/logs/:/var/log/nginx/
      - ../public:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  congratulations_typescript:
    tty: true
    ports:
      - 9005:9005
    build: ./typescript/
    working_dir: /workspace/
    container_name: congratulations_typescript_container
    volumes:
      - ./workspace/:/workspace/
      - ../public/:/workspace/public/
      - ../public/dist/:/workspace/dist/
      - ../source/application/:/workspace/source/application/
